version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: staging
  reviewers:
  - biodrone
  assignees:
  - biodrone
  labels:
  - dependencies
