language: python
python:
  - "3.7"
  - "3.8"
dist: bionic

env:
  global:
    # DOCKER_PASSWORD
    - secure: "AlNoCd1sh1vQtRPNxpWuATFfxiQ6HkpOyXDbMiEqshaMg205ybspicb/3DJD6unnuSI50bA/Iz8ORxNxHED88q2aBfStWWOd3CgV13y4XZrsipeVAUV9V3NBJPVeAAoxP5a9a2hqWkywjqJ168c5Eh9o5a3gzQGgyZ0b92/jIc5Kxbl5id5DZiJN1xDkobPk6kwQUJGYn73hrG/YooMP6Ow/V2Xw2zmriDBDVYkzY6re2YtBdRC6176ecGQLRnAxQqcH4vhYxce4ewywCw/suzIiqnLBZxP9vVwXGvVpBBdK7BRJ3SY5C1Q18hEJYe1DpOd4BnqdjJB8RAc0DBwJIRuUAjZ2RPDALtiEi+RaQ5VnOblnDJgfDbNtg9hasvhZng760MbXt44oHxBuZzOGgtsA0jImHXJZD20Paqxntb26+bqaFV/H1p/vpHBb1jWz9xvqjmAZ6tQpQhxTPUmZWkbl3dzVB08YGDMS9EI4seUaeZPUZ5qjZc/v/UVOul/QskvZOAZonLzQ5i9Q1nu10NkVqBuwn7s9Dwc0hZ0wqFRqADtDuC3RAcDI1TxIMQuxNQCXBt57Jq81Uj6rl7yKM4K9pAKw7n6Wo2FgJqN3tobuo5Oz7tZJAPzbXkNzTtGLnDoOGw/n0kAEY2mA0/szBJfr4wFEm/+Q7KVJHOiszcg="
    # DOCKER_USER
    - secure: "v17uIDajBFDN0hhSI7DeRI2zR94KtB9qOXKK+qiPhSJaSCRlhVumo4MGbW9d4etYGbH7MihcACCfN8ML1ipF8uB6NsSwL2xk2ugA2KQqjoRgG1a1MNwOLWrh5CeCA4P8f1x0Id9YlRsvpPHV5Z04+QDBqVHq4N6303+GTD0JATILiUsCaRlZZnuZ8qFEvRpZGUstrpXqlnxNBoGPT1GPMucuonytxyzPsM6TS/6AMrkV6qQYT+6/K7koMb3rhEmHdMqqbPXfxpoCA2JWBE+aVeEb1XswYRL+CcL4ckLlkAKttH9PJEDcdUJuRLbrHajXStKTTiIMexzf/29/vJGLjyUYXyPbOowHULRoZk02fwJoFIMAHsWviOBe/+QF7R1lZLLytImNUxs+/Vs2l8N8mhRNJR2efiqfUiM2isFpEKRfYzVZEJ+iZho0wKnUvk5VdGO3qrr9eQIpmoV/36WF+2sjzRMLgjfBIR8g3xihe9QBbpO0uNkvNKrO8pmgolCgfV7cD2VC+6N+zLffYlQyFRmAf1TO9OFYGVibajjNsc/kDdDPv3HVAFqfYzNZgE/BbVYYiJRGuf+PG3oX+OO9qXHVA8k6fhJwFbGET9GMoqlCP4dzJtEmbUQCaICD37abSa+Kp1ayGhGE5SAhBt2mKMvzbPLjEhrl51ewTqT7hBw="

branches:
  only:
  - staging
  - master

stages:
  - pre-build
  - build
  - deploy-staging
  - deploy-stable

jobs:
  include:
  - stage: "pre-build"
    install:
    - pip install pipenv bandit
    - pipenv install -e .
    script:
    - pytest -v
    - bandit streamdl.py
  - stage: "build"
    language: shell
    services:
    - docker
    script:
    - docker build -t streamdl:build . --no-cache
  - stage: "deploy-staging"
    language: shell
    if: branch = staging
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t streamdl:staging .
    - docker images
    - docker tag streamdl:staging dangeroustech/streamdl:staging
    - docker push dangeroustech/streamdl:staging
  - stage: deploy-stable
    language: shell
    if: "branch = master"
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t streamdl .
    - docker tag streamdl dangeroustech/streamdl
    - docker push dangeroustech/streamdl
    - docker tag dangeroustech/streamdl dangeroustech/streamdl:stable
    - docker push dangeroustech/streamdl:stable

notifications:
  slack:
    secure: bQQS/eupev2ESGm8hBqgP6FEeOfQ2ifCpqsMvMuJkF6rQauEqBTdhQAwuQWJYdib5ILZDBbagF6ciPottjII4h88082nEb3qZFhnSM4jj2od5S6l1XugUfQhnFVcVV+Njpps82R2UfefuZKsQOWPimfRS9kFzkn2dByjJzupspC2nnPgtnw4NfMVo+JF3lAYcehvlC6e11PjcSVcqXEgTRTRqqk+Ve2dg/ID6JIbrAX8mOUwRnSnYi19X2NUgv8uaNS9GaWXgHa18/QqEWXacY0ca5jGfnHrSJpLOplcbr64MPuyQF5hKNUsndaCCcModhXYutnGTs4cX86+nIkEABhblOvOeB58tRt35UcwQP7Gkexbcvrd9Q09B2a64XiTyE7Hll2Hi1PBRYlCqu6l+SUJrkXMgifvsi2BrzEoy0f00otZeTrGhNyQzsWXO8hGxDbO6F+0JpPG4H3f4QbodoIFGaAPaIIXoiSUNKeCaWvKByRXIJi/U3viu+46KU2UmKkgwB7X7PUVfnxy4WnnApv+rD80mFkolLF3YFccys93eHxn2R2RDZqVBrd9aS6c7i8sMi1a6+IqqiZPf0aUqSPOsg5C8b3b1Mr16Vabm9Cml3fFYm6Y93Rbo9CI0bIhx4XAIiwNASToBVMMQlUiax4+PwaTzCQzGo0yG4zRqhk=
