branches:
  only:
  - staging
  - master
language: python
python:
- '3.7'
install:
- pip install pipenv
- pipenv install -e .
script: pytest
notifications:
  slack:
    on_success: always
    secure: lm2pARlEFbq2a7X5oQgxk4n4P17Gz/hspYLh8dRs9u0XPLiUuI/Rhs6/Jk2u64OJHBaTOcFmaw02EX4BYleonTEzcVHK7m6itmAnIIkBng54e01sgEv2AeqkEyfXAUkD9VQvtOoWlyS8hBE8Szvw0uTwJWBfXxgMY6LbLU0/1iBoyPQhkc3FinrFGTnjbPSoBffitEWDWO14iH+nASEzZIPYRjGEftKfqqZHCBE6zDEjNDzEFhcFz5KeFRteDK6gwvwiUHw0iU/6G7XhUFEKKIewSBO0NYM3WMHtObt4zr7Aqw6EBoaBCOx7niIRpICtVbD5WcaAdsPUSWf+2pQ267rXx5x7yKtcHawXJnLvLoA/IC3TQA3DgZpBH0hXoljXfZ9Jia0IEufKuVPf+UlPa21vAtfWpk49zfIXutRnpqxm3Cmx3b1bVZdiK/nzmF9ylULmQwLLoaiuI1JyCtBSOR48eovvkTA0RF8z1UaCe7R7GimWgn+2lL4LHtyAza3f1sTXhNF0SAJKqWrlJnMRi/9bDwl8vVzpJUS8TtdZvSTkOD95UleozXioVgylnDtzbDLgdcbYEt0jLC01MHDrXrZDCLkaVUehc01enk+dhk0/p4PU+j5lQJQHsqxO04CHyzXGpqKIwXRh41jhxj2iQ6Vi4NvJDqoKmHY4s+1G5kE=
