branches:
  only:
  - staging
  - master
language: python
python:
- '3.7'
install:
- pip install pipenv
- pipenv install -e .
script: pytest
notifications:
  slack:
    secure: Oz15OSk+30mh19R644iTX2c4BeSqAACM+HmGnYlxS+RCLlQ8q+qEFY51lbsZX8c9fHOQ0D4sHE44UBYLlNQEbutq8HOEHuZgHrceJdatTKLpI+v3jssdIsUVMIrzjn34sGawAnxJiNelEEO9SiNmK5ytcJrTxTxY0kG1Mzi52keP/aZVtT3QuZsrgakwGkhVmmJOuuNFswD2h2wnUkkTWjJmrJhQy0FEYh9AgCkBe3fAOGh3Bu301sHDcRi5/5/8qNo8H6RInRQv3qC714T5FU7q09NVuRnxKzDzyQdQdL/jM2S5ZJbpTwuRHWZuZ6436P4t0t3jpySOILqCnpeMgRH8ssEJ34b9FPBea6TZbBER3q5D9gmXwmtna5u9aZJeYyjqLY0bBUXcFBENX60b4iPm0DHIgI9uhtgDoStUEsEX6TzsdCtaFwSamt9SzoW79IXBn950uUFWSVtIKzQ3cIFnO6Mi3QpygLiUmUJ07huGmhAwdiuRDfHJXruzsGrnxCS5KKwsxYd38kjBp0n8R7RBnaYp99gZHv1pUHBqPsT4anRUfzmBnP4T+vbT+epKyhlkaF1A8vDqCBeiu0byRNc2ZbEaQ8/fUqK7Xh+Pr2YiDODyI7kWUlF3Rq0RUbKyQvRGUHp3qDcMAkDKelO1/Jn5FThHaZt3+Whifnxfv2g=
