dist: bionic

env:
  global:
    # DOCKER_PASSWORD
    - secure: "tdH9nwfuO5cC7lEuOYyp8U/YB44yq7ebceLYtpEqKx4STYs1T8CMVFpo5loL+cjfcsxbbJM13Om7y+Bt+Zv+ir0fGG3E4likOhjaEXI8pD/yoVgn65ezMJi0fYLLUBDHs6LpVJwB5etbec+Xkj300t4koh0+HOSEzeoSx0aFA0FbxZRHbSKQ7pKQN34YTJUCTnRUxVfFySOHUqYRRXeh/HCr3YHNBP+jlWObDvhk/TkIdJQjABdFU68HCUPeErhK00oWHyVqYi+I4FfMmFKYNhJ/XJq6dKIrn/j3bvQ7XmBLjLoe2j1qugFA2WL79KoE5WxydXMXQ6472sMWeE8YAMUZzqmuVTMZEZuyQc61jlt714cux4z+zULbx2E9AgsybayreGRkfij0n3OFKra8wtw7p8On1KuopIWaNlAzyxsKbcNHPUHgjjIxFOFkdnBm4iSYDoh7T6q2A612chQE+uBB0FtD8sags6rM6Myd5s4K7rHGoO4DnaAza6t+cky7ynv2glAnzOlWTzcuaz7WynI0efd1E8+JZllIr89Mpwp96CW+5PmTI4FCsZNkCDuuJT9+o75neK1yy+0J4qpicE/PFMkD3a7CvcjG60UOwLbBHipOW/YaOefThQIz7bXbd+X2y8daaHZ7ekPMtKz9aC2rNr6wgCNITqZ5oQWzqDM="
    # DOCKER_USER
    - secure: "UCErWApGLigqHfGGQqF+OHaeQa21dtl2fJOAYGSgYO3TTk/AgvHWWeK5qeGIBMDqMGZKlvizOEEkPEEZGNDqicAwpIGtrmHqM/j6dWOl4mnQ9SSb4lRZtwsShXi5Z0zhyeEVe8HD94MaU89b8wXgjo9k3JU81JFhEolFTsnnzV7tD9CyECvwRqS+YAwu4szKUEutuP85H/KoP5dwv/doTHm94MbTc0ursHgWMnDdU+nESECKUF1fmPlP2jw/TAbacBy3av50WyOCkx4liRfcVPik3KAd8qpNpyinOJOpFFuutHm49+sKeCFUg961NtQtZRepiPjrJ1/N9eXXOIy51f8M1zCT+DY1ubVDjJH+zy1uUwbVmuYs44Y5/L+AEIXS9ds7FR2TmCNlGlC5DhJOt2pVGxy/oBFsp383tAq+tIPaBRjRkJY3pvhEwyyr03MN2mU7jM8m12aui12KTArTUx2c1/gLyj4TX9ezV34TczR+y7u4dsXCkkib0zGm5g73tges292oR3Wjlc6B3+UURh2oHnhgCg03MiE4F1XTT8jNmoPv/Kn6928+BjKlZuMfqUYLdnvpeOY0h6XFNZK2JPjzDbK1O18INrE9CWWPP3L6kWOeIA6N0gkCKyLF3hyBqd9dHuO/9d9sZdgirfM+d4mHzI19VSKlmK4/qiWtmw0="


branches:
  only:
  - staging
  - master

stages:
  - pre-build
  - build
  - deploy

jobs:
  include:
  - stage: "pre-build"
    language: python
    python:
    - '3.7.5'
    install:
    - pip install pipenv bandit
    - pipenv install -e .
    script:
    - pytest -v
    - bandit streamdl.py
  - stage: "build"
    language: shell
    services:
    - docker
    script:
    - docker-compose build --no-cache
  - stage: deploy
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t streamdl .
    - docker images
    - docker tag streamdl dangeroustech/streamdl
    - docker push dangeroustech/streamdl:latest

notifications:
  slack:
    secure: bQQS/eupev2ESGm8hBqgP6FEeOfQ2ifCpqsMvMuJkF6rQauEqBTdhQAwuQWJYdib5ILZDBbagF6ciPottjII4h88082nEb3qZFhnSM4jj2od5S6l1XugUfQhnFVcVV+Njpps82R2UfefuZKsQOWPimfRS9kFzkn2dByjJzupspC2nnPgtnw4NfMVo+JF3lAYcehvlC6e11PjcSVcqXEgTRTRqqk+Ve2dg/ID6JIbrAX8mOUwRnSnYi19X2NUgv8uaNS9GaWXgHa18/QqEWXacY0ca5jGfnHrSJpLOplcbr64MPuyQF5hKNUsndaCCcModhXYutnGTs4cX86+nIkEABhblOvOeB58tRt35UcwQP7Gkexbcvrd9Q09B2a64XiTyE7Hll2Hi1PBRYlCqu6l+SUJrkXMgifvsi2BrzEoy0f00otZeTrGhNyQzsWXO8hGxDbO6F+0JpPG4H3f4QbodoIFGaAPaIIXoiSUNKeCaWvKByRXIJi/U3viu+46KU2UmKkgwB7X7PUVfnxy4WnnApv+rD80mFkolLF3YFccys93eHxn2R2RDZqVBrd9aS6c7i8sMi1a6+IqqiZPf0aUqSPOsg5C8b3b1Mr16Vabm9Cml3fFYm6Y93Rbo9CI0bIhx4XAIiwNASToBVMMQlUiax4+PwaTzCQzGo0yG4zRqhk=
