image: atlassian/default-image:2

pipelines:
  default:
    - step:
        caches:
          - docker
        services:
          - docker
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $BITBUCKET_COMMIT .
