[tool.poetry]
name = "StreamDL"
version = "1.2.5"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [
    "biodrone"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
youtube_dl = "2021.6.6"
PyYAML = "6.0"
requests = "2.26.0"
streamlink = "^3.0.1"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
pylint = "^2.10.2"
