[tool.poetry]
name = "StreamDL"
version = "3.0.0"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [ "biodrone <biodrone@dangerous.tech>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
grpcio = "^1.43.0"
protobuf = "^3.19.4"
streamlink = "^4.3.0"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
black = "^22.1"
