[tool.poetry]
name = "StreamDL"
version = "1.2.5"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [
    "biodrone"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
youtube_dl = "2021.12.17"
PyYAML = "6.0"
requests = "2.27.1"
streamlink = "^2.4.0"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
pylint = "^2.12.2"
