[tool.poetry]
name = "StreamDL"
version = "2.0.2"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [ "biodrone <biodrone@dangerous.tech>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "6.0"
requests = "2.27.1"
streamlink = "^3.1.1"
yt-dlp = "^2022.1.21"
ffmpeg-python = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
black = "^21.12b0"
