[tool.poetry]
name = "StreamDL"
version = "3.1.12"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [ "biodrone <biodrone@dangerous.tech>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
grpcio = "^1.59.0"
protobuf = "^4.24.3"
streamlink = "^6.2.1"
wheel = "^0.41.2"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
black = "^23.7"
