[tool.poetry]
name = "StreamDL"
version = "3.1.3"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [ "biodrone <biodrone@dangerous.tech>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
grpcio = "^1.54.0"
protobuf = "^4.22.3"
streamlink = "^5.4.0"
wheel = "^0.40.0"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
black = "^23.3"
