[tool.poetry]
name = "StreamDL"
version = "1.2.5"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [
    "biodrone"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
youtube_dl = "2021.6.6"
PyYAML = "5.4.1"
requests = "2.26.0"
streamlink = "^2.2.0"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
pylint = "^2.9.1"
