[tool.poetry]
name = "StreamDL"
version = "1.2.9"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [ "biodrone <biodrone@dangerous.tech>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "5.4.1"
requests = "2.26.0"
streamlink = "^3.0.3"
yt-dlp = "^2021.12.27"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
black = "^21.12b0"
