[tool.poetry]
name = "StreamDL"
version = "3.1.24"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [ "biodrone <biodrone@dangerous.tech>" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
grpcio = "^1.60.0"
protobuf = "^4.25.2"
streamlink = "^6.5.1"
wheel = "^0.42.0"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
black = "^24.3"
