[tool.poetry]
name = "StreamDL"
version = "1.2.4"
description = "Monitor and Download Streams from a Variety of Websites"
authors = [
    "biodrone"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
youtube_dl = "2020.5.3"
PyYAML = "5.3.1"
requests = "2.23.0"

[tool.poetry.dev-dependencies]
pytest = "*"
bandit = "*"
