name: "Dockerhub Build"

on:
  push:
    branches: [ master ]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: dangeroustech/streamdl:latest

      - name: Version
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-bump-patch-version: true
          changelog-generator-opt: "emojis=true"
          changelog-file: "CHANGELOG.md"
          prepend: true
          update-file: pyproject.toml

      - name: Dockerhub Push Stable
        id: dockerhub_stable_push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/armhf
          push: true
          tags: |
            dangeroustech/streamdl:latest
            dangeroustech/streamdl:stable
