name: "Dockerhub Build - Staging"

on:
  push:
    branches: [ staging ]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component: ["client", "server"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.${{ matrix.component }}
          load: true
          tags: dangeroustech/streamdl:${{ matrix.component }}_latest

      - name: Dockerhub Push Staging
        id: dockerhub_staging_push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.${{ matrix.component }}
          platforms: linux/amd64
          push: true
          tags: |
            dangeroustech/streamdl:${{ matrix.component }}_latest
            dangeroustech/streamdl:${{ matrix.component }}_staging
      
      - name: Snyk Scan
        id: snyk_scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: dangeroustech/streamdl:${{ matrix.component }}_staging
          args: --severity-threshold=medium --file=Dockerfile.${{ matrix.component }}
      
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
