name: "Dockerhub Build - Master"

on:
  push:
    branches: [ master ]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.example
          load: true
          tags: dangeroustech/streamdl:latest

      - name: Changelog
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version} [skip ci]'
          force-bump-patch-version: true
          changelog-generator-opt: "emojis=true"
          output-file: "CHANGELOG.md"
          tag-prefix: 'v'
          release-count: 0
          version-file: pyproject.toml

      - name: Create Release
        uses: actions/create-release@v1
        id: release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Dockerhub Push Stable
        id: dockerhub_stable_push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.example
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            dangeroustech/streamdl:latest
            dangeroustech/streamdl:stable
            dangeroustech/streamdl:${{ steps.changelog.outputs.tag }}
