name: "Deploy"

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - run: |
          python -m pip install poetry bandit
          python -m poetry install
          python -m poetry run pytest -v
          python -m poetry run bandit -ll -c .bandit.yml streamdl.py

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/armhf
          push: true
          tags: dangeroustech/streamdl:lates
