name: StagingWorkflow

on:
  push:
    branches: 
      - staging
  pull_request:
    branches: 
      - staging
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
    steps:
      - name: Checkout Staging
        uses: actions/checkout@v1
        
      - name: Python Run
        shell: python
        run: |
          pip install pipenv
          pipenv install -e .
          pipenv run python3 cbdl.py --help
